# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Surbhi Chaturvedi
title: Graduate MIS Student '2020
email: surbhichaturvedi@email.arizona.edu
mobile: 520-257-8809
website: surbhichats.github.io/surbhichaturvedi

# Social links
#twitter_username: facespics
github_username:  http://github.com/surbhichats/surbhichaturvedi
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: http://www.instagram.com/surbhichats
linkedin_username: http://www.linkedin.com/in/surbhichaturvedi
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/SurbhiC.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a Graduate student at the Eller College of Management - University of Arizona. I am pursuing Masters' Management Information System with a concentration in Business Intelligence and Analytics.

  I have over a decade of experience in Project Management working on Agile based projects. I want to apply my past experience and current coursework (sppecialization in Business Intelleigence and Analytics).

  to create engaging customer experience.

# Projects Section
# projects_title: Academic Projects

# Education Section
# educaton_title: Education

# Experience Section
# experience_title: Experience

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests project and product management some of my other interests and hobbies are:
   - Reading
   - Volunteering
   - Watching Movies
   - Tinkering with this website and learning new coding techniques

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
